## ********************************************************** ##
# Author:       Muhammad Ahmad
# Email:        muhammadmoustafa@eng1.cu.edu.eg
# Affiliation:  Systems and Biomedical Engineering Department
#               Faculty of Engineering
#               Cairo University
## ********************************************************** ##

#### global constants ####
par ampPar=0

TEMP=36
CM=0.001
Ra=70
vtraub=-10
vtraub2=-70
tadj=3^((TEMP-36)/10)
tadj20=3^((TEMP-36)/10)
tadj23=3^((TEMP-36)/10)
FARADAY=96484.56
R=8.31441
CaDen_Max=0.000168
isActive=1

#done