## ********************************************************** ##
# Author:       Muhammad Ahmad
# Email:        muhammadmoustafa@eng1.cu.edu.eg
# Affiliation:  Systems and Biomedical Engineering Department
#               Faculty of Engineering
#               Cairo University
## ********************************************************** ##



# bifurcation max value
# Note: setting maxAmp below 50 causes max out in bifurcation, 2000 is good, NTST=100
## stimulus current in nA, 10^-6 is the conversion factor to nA
maxAmp=50
I=ampPar*maxAmp*10^(-6)
@ total=200
@ xhi=200

#done